version: "3.9"

services:

  mysql:
    image: martnsdev/mysql-ms:1.0
    container_name: mysql-ms
    environment:
      MYSQL_ROOT_PASSWORD: 5517
      MYSQL_DATABASE: alurafood
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  pedidos:
    image: martnsdev/pedidos-ms:1.3
    container_name: pedidos-ms
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/alurafood
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 5517
    ports:
      - "8081:8080"

  pagamentos:
    image: martnsdev/pagamentos-ms:1.0
    container_name: pagamentos-ms
    depends_on:
      - mysql
    ports:
      - "8082:8080"

  gateway:
    image: martnsdev/gateway-ms:1.0
    container_name: gateway-ms
    depends_on:
      - pedidos
      - pagamentos
    ports:
      - "8080:8080"

volumes:
  mysql_data:
